# Generated by Django

from django.db import migrations, models
import django.db.models.deletion
import uuid

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(default='Cleveland, OH', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('experience_level', models.CharField(default='Entry Level', max_length=50)),
                ('salary_range', models.CharField(blank=True, help_text='e.g., $60,000 - $75,000', max_length=100, null=True)),
                ('skills_required', models.CharField(help_text='e.g., JavaScript, React, SQL', max_length=255)),
                ('certs_recommended', models.CharField(blank=True, help_text='e.g., Security+, AWS Cloud Practitioner', max_length=255, null=True)),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='1-5 Scale')),
                ('hiring_experience', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='jobs.jobposting')),
            ],
        ),
    ]
