# Generated by Django 4.2.29 on 2026-04-02 00:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(default='Cleveland, OH', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(default='Cleveland, OH', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('experience_level', models.CharField(default='Entry Level', max_length=50)),
                ('salary_range', models.CharField(blank=True, help_text='e.g., $20/hr - $30/hr', max_length=100, null=True)),
                ('skills_required', models.CharField(max_length=255)),
                ('certs_recommended', models.CharField(blank=True, max_length=255, null=True)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('certifications', models.ManyToManyField(blank=True, to='jobs.certification')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.company')),
                ('roles', models.ManyToManyField(blank=True, to='jobs.role')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('pros', models.TextField()),
                ('cons', models.TextField()),
                ('interview_process', models.TextField()),
                ('recommendation', models.TextField()),
                ('skills_used', models.CharField(max_length=255)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='jobs.company')),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('skills', models.CharField(max_length=255)),
                ('is_mentor', models.BooleanField(default=False)),
                ('graduation_year', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.company')),
            ],
        ),
    ]
