# Generated by Django 4.2.29 on 2026-04-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_certification_description_certification_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='certs_recommended',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='skills_required',
        ),
    ]
