# Generated by Django 4.2.29 on 2026-04-17 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_jobposting_certs_recommended_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('position_type', models.CharField(choices=[('internship', 'Internship'), ('co_op', 'Co-op'), ('part_time', 'Part-time'), ('entry_level', 'Entry-level')], max_length=50)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('year', models.PositiveIntegerField()),
                ('benefits', models.TextField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_reports', to='jobs.company')),
            ],
        ),
    ]
