# Generated by Django 4.2.29 on 2026-04-17 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0007_companyreview_moderated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_job_postings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='rejection_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('rejected', 'Rejected')], default='published', max_length=20),
        ),
    ]
