# Generated by Django 4.2.29 on 2026-04-18 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobposting_rejected_at_jobposting_rejected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='advice_for_students',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alumni',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='alumni',
            name='experience_highlights',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alumni',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alumni',
            name='how_they_got_there',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alumni',
            name='internship_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alumni',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alumni',
            name='open_to_questions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='open_to_referrals',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='jobs.company'),
        ),
    ]
